---
title: "Ejemplo viñeta"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Ejemplo viñeta}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE,
                      comment = "#>")

knitr::knit_hooks$set(
  margin = function(before, options, envir) {
    if (before) {
      par(mar = c(0.1, 0.1, 1.3, 0.1))
    }
  }
)


```


# Introducción 

Este paquete es un *proof of concept* sobre cómo crear una plantilla de `pkgdown` adaptada. En este paquete la plantilla base que se adaptará se basa en la empleada por la comunidad [rOpenSpain](https://ropenspain.es/), que a su vez es una adaptación de la plantilla [Universal](https://bootstrapious.com/p/universal-business-e-commerce-template) creada por Bootstrapius con la variación de color **violet**.

## Limitaciones

El diseño original de las plantillas que componen `pkgdown` es bastante rígido, en el sentido de que ligeras modificaciones (como el tipo de navbar o la localizaxion del footer) pueden provocar que el renderizado final no sea óptimo. Para solucionarlo se han empleado algunos *hacks* en el fichero `css` y pequeños fragmentos en `javascript`.

Otra limitación es la diferencia de versiones Bootstrap, ya que `pkgdown` emplea la versión 3.4.1 mientras que Universal emplea la 3.3.7.
  

# Configuración

En la raíz del proyecto ha de existir un archivo `_pkgdown.yaml` con al menos las siguientes líneas:

``` yaml
template:
  package: tidytemplate
  # No pongas la siguiente línea!
  default_assets: false

```

Puedes encontrar información sobre cómo configurar otras opciones en `_pkgdown.yaml` [aquí](https://pkgdown.r-lib.org/articles/pkgdown.html).

# Instrucciones de uso

## Con GitHub actions - Automático

### Branch gh-pages



### Branch main/master

## Con RStudio - Manual

### Branch main/master
