---
title: "Cómo usar esta plantilla"
output: 
  rmarkdown::html_vignette:
    toc: true
    number_sections: true 
    toc_depth: 1
vignette: >
  %\VignetteIndexEntry{Cómo usar esta plantilla}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE,
                      comment = "#>")

knitr::knit_hooks$set(
  margin = function(before, options, envir) {
    if (before) {
      par(mar = c(0.1, 0.1, 1.3, 0.1))
    }
  }
)


```


# Introducción 

Este paquete es un *proof of concept* sobre cómo crear una plantilla de `pkgdown` adaptada. En este paquete la plantilla base que se adaptará se basa en la empleada por la comunidad [rOpenSpain](https://ropenspain.es/), que a su vez es una adaptación de la plantilla [Universal](https://bootstrapious.com/p/universal-business-e-commerce-template) creada por Bootstrapius con la variación de color **violet**.

## Limitaciones

El diseño original de las plantillas que componen `pkgdown` es bastante rígido, en el sentido de que ligeras modificaciones (como el tipo de navbar o la localizaxion del footer) pueden provocar que el renderizado final no sea óptimo. Para solucionarlo se han empleado algunos *hacks* en el fichero `css` y pequeños fragmentos en `javascript`.

Otra limitación es la diferencia de versiones Bootstrap, ya que `pkgdown` emplea la versión 3.4.1 mientras que Universal emplea la 3.3.7.
  

# Configuración

En la raíz del proyecto ha de existir un archivo `_pkgdown.yaml` con al menos las siguientes líneas:

``` yaml
template:
  package: rostemplate
  # No pongas la siguiente línea!
  default_assets: false

```

Puedes encontrar información sobre cómo configurar otras opciones en `_pkgdown.yaml` [aquí](https://pkgdown.r-lib.org/articles/pkgdown.html).

# Uso de la plantilla

Esta sección detalla diferentes opciones para generar un sitio estático para el paquete deseado con el formato definido por esta plantilla. El resultado de este paso es la generación de un sitio estático compuesto de los archivos `html`, `css`, etc. basados en el paquete de R para el que se está generando el sitio.


## Con GitHub actions - CI

GitHub Actions permite automatizar procesos cuando se activa un trigger. En este caso se han preparado dos acciones que actualizan el sitio estático cada vez que se añade un *commit* al repositorio. 

Los flujos de trabajo consisten en archivos con extensión `.yaml`. La acción [rostemplate-docs.yaml](https://github.com/dieghernan/rostemplate/blob/main/inst/yaml/rostemplate-docs.yaml) crea el sitio estático en la carpeta `./docs` mientras que [rostemplate-gh-pages.yaml](https://github.com/dieghernan/rostemplate/blob/main/inst/yaml/rostemplate-gh-pages.yaml) crea el sitio estático en el branch `gh-pages`.

Para configurar esta opción, es necesario disponer en el repositorio de una carpeta en la ruta `.github/workflows` y copiar la acción deseada en dicha carpeta.

Es posible cambiar el evento que desencadena la actualización del sitio:

```yaml 

# Actualiza en cada commit - por defecto
on:
  push:
    branches:
      - main
      - master
      
# Actualiza cuando se modifica un archivo específico: _pkgdown.yaml

on:
  push:
    paths:
      - '_pkgdown.yaml'

```

Más información [aquí](https://docs.github.com/es/free-pro-team@latest/actions/reference/events-that-trigger-workflows).

## RStudio - manual

El sitio estático se puede generar igualmente desde una sesión local en RStudio. Para ello, es necesario instalar este paquete en el ordenador y luego usar las funcionalidades propias de `pkgdown`:

```r
install.packages('remotes')
install.packages('pkgdown')

remotes::install_github("dieghernan/rostemplate")

pkgdown::build_site()

```

Es necesario actualizar el repositorio remoto en GitHub tras ejecutar el script anterior.

# GitHub Pages

Una vez generado el sitio estático y subido al repositorio en GitHub, el último paso es generar el sitio web a través de los Settings de nuestro repositorio, seleccionando el origen deseado (`gh-pages`, `main/docs`, etc.).


