# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    tags: ["*"]
  release:
    types: [published]
  workflow_dispatch:

name: rostemplate-docs
permissions: write-all
# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  rostemplate-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::pkgdown
            ropenspain/rostemplate
          needs: website

      - name: Deploy package
        run: |
          Rscript -e 'pkgdown::clean_site()'
          Rscript -e 'pkgdown::build_site(new_process = FALSE)'

      - name: Commit results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m 'Build pkgdown' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
