---
title: "Descargas de paquetes de rOpenSpain"
---

*Fecha de actualización: `r format(Sys.Date(),"%d %b %Y")`*

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  tidy = "styler",
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  dev = "ragg_png",
  dpi = 300,
  out.width = "100%"
)
```

## En CRAN

Descargas de paquetes de [rOpenSpain](https://ropenspain.es/) desde CRAN.

```{r include=FALSE}
library(cranlogs)
library(tibble)
library(dplyr)
library(tidyverse)
library(rostemplate)

Sys.setenv("R_CRAN_WEB" = "https://cloud.r-project.org")
crandb <- unique(tools::CRAN_package_db()$Package)


mypaks <- jsonlite::read_json(
  paste0(
    "https://raw.githubusercontent.com/rOpenSpain/rOpenSpain.",
    "r-universe.dev/master/packages.json"
  )
) %>%
  lapply(function(x) {
    x[["package"]]
  }) %>%
  unlist() %>%
  unique()

# Packages in CRAN
mypaks <- mypaks[mypaks %in% crandb]

dwn <- lapply(mypaks, cranlogs::cran_downloads, from = "2016-01-01")

dwn <- dwn %>%
  bind_rows() %>%
  as_tibble()

# First date on CRAN

first_date_on_cran <- function(pkg) {
  all <- pkgsearch::cran_package_history(pkg)

  d <- all %>%
    select(`Date/Publication`) %>%
    slice_head(n = 1) %>%
    pull() %>%
    as.Date()

  lv <- all %>%
    select(`Date/Publication`) %>%
    slice_tail(n = 1) %>%
    pull() %>%
    as.Date()

  df <- tibble(package = pkg, date = d, lv = lv)
  df
}

fechas <- lapply(unique(dwn$package), first_date_on_cran) %>%
  bind_rows()

dwn <- dwn %>%
  left_join(fechas %>% select(package, d_cran = date)) %>%
  filter(date >= d_cran) %>%
  select(-d_cran) %>%
  tidyr::replace_na(list(count = 0)) %>%
  filter(date < Sys.Date())

# By month
library(lubridate)


dwn_m <- dwn %>%
  mutate(m = lubridate::ceiling_date(dwn$date, "month") - 1) %>%
  group_by(package, m) %>%
  summarise(downloads = sum(count))


# factors by first date on CRAN
fact <- fechas %>%
  arrange(date) %>%
  pull(package) %>%
  unique() %>%
  rev()

dwn_m$package <- factor(dwn_m$package, levels = unique(fact))
```

### Histórico de descargas

```{r echo=FALSE}
tot <- dwn_m %>%
  group_by(m) %>%
  summarise(ntot = sum(downloads))

ggplot(dwn_m, aes(x = m)) +
  geom_col(aes(y = downloads, fill = package)) +
  geom_smooth(data = tot, aes(m, ntot), color = "grey40", se = TRUE) +
  theme_minimal() +
  scale_fill_manual(values = ros_qualitative_pal(length(fact),
    rev = TRUE, alpha = 0.75
  )) +
  scale_y_continuous(labels = scales::label_comma()) +
  labs(
    fill = "Paquete",
    x = "",
    y = "# descargas semanales"
  ) +
  theme(axis.title = element_text(size = 8))
```

### Descargas semanales

```{r echo=FALSE}
dwn_w <- dwn %>%
  filter(date >= (Sys.Date() - years(1))) %>%
  mutate(m = lubridate::ceiling_date(date, "week")) %>%
  group_by(package, m) %>%
  summarise(downloads = sum(count))

dwn_w$package <- factor(dwn_w$package, levels = unique(rev(fact)))

dwn_w %>%
  ggplot(aes(x = m)) +
  geom_area(aes(y = downloads), fill = ros_green_pal(1, alpha = 0.75)) +
  geom_smooth(aes(y = downloads), color = ros_violet_pal(1), se = FALSE) +
  facet_wrap(vars(package)) +
  scale_x_date(
    date_breaks = "3 months",
    labels = scales::label_date("%Y-%m")
  ) +
  theme_minimal() +
  scale_y_continuous(labels = scales::label_comma()) +
  labs(
    fill = "Paquete",
    x = "",
    y = "# descargas semanales"
  ) +
  theme(
    axis.title = element_text(size = 8),
    axis.text.x = element_text(size = 6)
  )
```

### Datos sobre descargas

```{r datos, echo=FALSE}
library(reactable)
library(htmltools)

lastyear <- dwn %>%
  filter(date >= (Sys.Date() - 365)) %>%
  group_by(package) %>%
  summarise(last_year = sum(count, na.rm = TRUE))


lastmonth <- dwn %>%
  filter(date >= (Sys.Date() - months(1))) %>%
  group_by(package) %>%
  summarise(last_month = sum(count, na.rm = TRUE))

lastweek <- dwn %>%
  filter(date >= (Sys.Date() - 7)) %>%
  group_by(package) %>%
  summarise(last_week = sum(count, na.rm = TRUE))

last_day <- dwn %>%
  filter(date == max(dwn$date, na.rm = TRUE) - 1) %>%
  select(package, last_day = count)

avg_daily <- dwn %>%
  group_by(package) %>%
  summarise(avg = round(mean(count, na.rm = TRUE), 1))

avg_daily_all <- avg_daily %>%
  ungroup() %>%
  summarise(avg = round(sum(avg, na.rm = TRUE), 1))

# Une todo y da nombres
end <-
  fechas %>%
  left_join(avg_daily) %>%
  left_join(last_day) %>%
  left_join(lastweek) %>%
  left_join(lastmonth) %>%
  left_join(lastyear) %>%
  as_tibble() %>%
  arrange(desc(avg))

names(end) <- c(
  "paquete",
  "en CRAN desde",
  "Versión en CRAN",
  "media diaria", "último dia",
  "última semana", "último mes", "último año"
)

react_es <- reactableLang(
  sortLabel = "Ordena {name}",
  filterPlaceholder = "",
  filterLabel = "Filtro {name}",
  searchPlaceholder = "Búsqueda",
  searchLabel = "Búsqueda",
  noData = "Sin resultados",
  pageNext = "Siguiente",
  pagePrevious = "Anterior",
  pageNumbers = "{page} de {pages}",
  pageInfo = "{rowStart}\u2013{rowEnd} de {rows} registros",
  pageSizeOptions = "Mostrando {rows}",
  pageNextLabel = "Siguiente página",
  pagePreviousLabel = "Página anterior",
  pageNumberLabel = "Página {page}",
  pageJumpLabel = "Ir a página",
  pageSizeOptionsLabel = "Registros por página"
)

options(reactable.language = react_es)

reactable(
  end,
  filterable = TRUE,
  searchable = TRUE,
  showPageSizeOptions = TRUE,
  striped = TRUE,
  defaultColDef = colDef(
    minWidth = 150, vAlign = "center", footerStyle = list(fontWeight = "bold"),
    footer = function(values) {
      if (!is.numeric(values)) {
        return()
      }
      prettyNum(sum(values), big.mark = ".", decimal.mark = ",")
    }
  ),
  paginationType = "jump",
  elementId = "cran-dwn",
  columns <- list(
    paquete = colDef(
      cell = function(value) {
        # Render as a link
        url <- paste0("https://CRAN.R-project.org/package=", value)
        badge <- paste0("https://badges.cranchecks.info/worst/", value, ".svg")
        link <- htmltools::a(href = url, target = "_blank", as.character(value))
        div(
          div(link, style = list(fontWeight = "bold")),
          div(htmltools::img(src = badge, alt = as.character(value)),
            style = list(fontSize = "75%")
          )
        )
      },
      align = "left",
      sticky = "left",
      rowHeader = TRUE
    ),
    "media diaria" = colDef(
      format = colFormat(separators = TRUE),
      footer = function(values) {
        p <- round(avg_daily_all$avg, 2)
        prettyNum(p, big.mark = ".", decimal.mark = ",")
      }
    ),
    "último dia" = colDef(format = colFormat(separators = TRUE)),
    "última semana" = colDef(format = colFormat(separators = TRUE)),
    "último mes" = colDef(format = colFormat(separators = TRUE)),
    "último año" = colDef(format = colFormat(separators = TRUE))
  )
)
```

## En Posit Package Manager

Descargas de paquetes de [rOpenSpain](https://ropenspain.es/) y metadatos desde
[Posit Package Manager](https://packagemanager.posit.co/client/#/).

```{r data-posit, echo=FALSE}
res <- lapply(mypaks, function(x) {
  tmp <- tempfile(fileext = ".json")
  api_res <- suppressWarnings(try(download.file(
    paste0("https://packagemanager.posit.co/__api__/repos/1/packages/", x),
    tmp,
    quiet = TRUE
  ), silent = TRUE))

  if (inherits(api_res, "try-error")) {
    return(NULL)
  }

  info <- jsonlite::read_json(tmp)

  df_init <- as_tibble(
    info[c("name", "date_publication", "package_size", "version")]
  )


  df_prep <- df_init %>%
    mutate(
      date_in_cran = as.Date(date_publication),
      psize = paste(round(package_size / (1024^2), 2), "Mb"),
      mdown = as.integer(info$downloads)
    ) %>%
    select(
      package = name,
      lvers = version,
      date_in_cran, psize, mdown
    )


  df_prep
})

res_all <- bind_rows(res) %>%
  arrange(desc(mdown))

names(res_all) <- c(
  "paquete", "Última version", "en CRAN",
  "Tamaño", "Descargas (último mes)"
)


reactable(
  res_all,
  filterable = TRUE,
  searchable = TRUE,
  showPageSizeOptions = TRUE,
  striped = TRUE,
  defaultColDef = colDef(
    minWidth = 150, vAlign = "center", footerStyle = list(fontWeight = "bold"),
    footer = function(values) {
      if (!is.numeric(values)) {
        return()
      }
      prettyNum(sum(values), big.mark = ".", decimal.mark = ",")
    }
  ),
  paginationType = "jump",
  elementId = "posit-dwn",
  columns = list(
    paquete = colDef(
      cell = function(value) {
        # Render as a link
        url <- paste0("https://CRAN.R-project.org/package=", value)
        link <- htmltools::a(href = url, target = "_blank", as.character(value))
        div(link, style = list(fontWeight = "bold"))
      },
      align = "left",
      sticky = "left",
      rowHeader = TRUE
    ),
    "Descargas (último mes)" = colDef(format = colFormat(separators = TRUE))
  )
)
```
